version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:3000
    depends_on:
      - backend 